AllCops:
  DisplayCopNames: true
  Exclude:
    - 'Rakefile'
    - 'vendor/**/*'

Naming/FileName:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Layout/LineLength:
  Max: 100

Metrics/ClassLength:
  Max: 120

Security/MarshalLoad:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/YodaCondition:
  # temporary work around for rubocop bug 'An error occurred while Style/YodaCondition...' (v0.49.1)
  Exclude:
    - 'spec/redis_session_store_spec.rb'
